### ISSUE TITLE
Thread workers not awaited on connection error

### ISSUE THREAD

**Issue by albertodonato** [RazerM/sqlalchemy_aio#18]
It some unittests, I'm sometimes getting warning about `Queue.get` not being awaited, or loop being closed.

I managed to get a simple reproducer test like this:

```python
import asyncio

import pytest
import sqlalchemy
from sqlalchemy_aio import ASYNCIO_STRATEGY
from sqlalchemy.exc import OperationalError


@pytest.mark.asyncio
async def test_sample(event_loop):
    engine = sqlalchemy.create_engine(
        'sqlite:////not-here', strategy=ASYNCIO_STRATEGY, loop=event_loop)
    with pytest.raises(OperationalError):
        await engine.connect()
```

The test always succeedss in my env, but I sometimes get warnings like:

```
test.py::test_sample
  /usr/lib/python3.7/asyncio/base_events.py:609: RuntimeWarning: coroutine 'Queue.get' was never awaited
    self._ready.clear()
```

or

```
Exception in thread Thread-1:                                                                                                                                                                                       
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ack/virtualenv/test/lib/python3.7/site-packages/sqlalchemy_aio/asyncio.py", line 37, in thread_fn
    self._request_queue.get(), self._loop)
  File "/usr/lib/python3.7/asyncio/tasks.py", line 813, in run_coroutine_threadsafe
    loop.call_soon_threadsafe(callback)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 733, in call_soon_threadsafe
    self._check_closed()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 480, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

It seems like worker threads are not always correctly awaited/collected in case of errors.

**Comment by RazerM** [comment]
0.14.1 released to PyPI

**Comment by albertodonato** [comment]
Thanks!
