### ISSUE TITLE
RuntimeError: Nursery is closed to new arrivals

### ISSUE THREAD

**Issue by mozesa** [RazerM/sqlalchemy_aio#35]
Dear @**RazerM**,

I just would like to point out that the following exception can happen: `RuntimeError: Nursery is closed to new arrivals`.

It goes away if I use some small value of sleep like `await trio.sleep(0.01)`.

The problem that if it happens (`RuntimeError`) then it _hides_ the root cause of exception. I mean first the _root_ exception happen but because of the lack of small sleep (canceled has raised) another exception `RuntimeError` happen. And finally I can see only this `RuntimeError`. Now it is super hard to debug. 😃 

Thanks for your help in advance.

**Updated snippet&traceback.**

```python
import trio
from sqlalchemy import Column, Integer, MetaData, Table, Text, create_engine
from sqlalchemy.exc import OperationalError
from sqlalchemy.schema import CreateTable
from sqlalchemy_aio import TRIO_STRATEGY


async def main():
    engine = create_engine("sqlite:///test.db", strategy=TRIO_STRATEGY)

    metadata = MetaData()
    users = Table(
        "users",
        metadata,
        Column("id", Integer, primary_key=True),
        Column("name", Text),
    )

    # Create the table
    try:
        await engine.execute(CreateTable(users))
        # await trio.sleep(0.01)
    except OperationalError:
        pass
    finally:
        raise Exception("The error msg that I would like to see again.")


if __name__ == "__main__":
    trio.run(main)
```

I left out the traceback.
```text
C:\Users\mozesa\PycharmProjects\asm-v316-web\.venv\Scripts\python.exe C:/Users/mozesa/PycharmProjects/asm-v316-web/asm_v316_web/__init__.py
Traceback (most recent call last):
  File "C:\Users\mozesa\PycharmProjects\asm-v316-web\.venv\lib\site-packages\trio\_core\_entry_queue.py", line 84, in task
    await self.wakeup.wait_woken()
  File "C:\Users\mozesa\PycharmProjects\asm-v316-web\.venv\lib\site-packages\trio\_core\_wakeup_socketpair.py", line 50, in wait_woken
    await _core.wait_readable(self.wakeup_sock)
  File "C:\Users\mozesa\PycharmProjects\asm-v316-web\.venv\lib\site-packages\trio\_core\_generated_io_windows.py", line 14, in wait_readable
    return await GLOBAL_RUN_CONTEXT.runner.io_manager.wait_readable(sock)
  File "C:\Users\mozesa\PycharmProjects\asm-v316-web\.venv\lib\site-packages\trio\_core\_io_windows.py", line 661, in wait_readable
    await self._afd_poll(sock, "read_task")
  File "C:\Users\mozesa\PycharmProjects\asm-v316-web\.venv\lib\site-packages\trio\_core\_io_windows.py", line 657, in _afd_poll
    await _core.wait_task_rescheduled(abort_fn)
  File "C:\Users\mozesa\PycharmProjects\asm-v316-web\.venv\lib\site-packages\trio\_core\_traps.py", line 166, in wait_task_rescheduled
    return (await _async_yield(WaitTaskRescheduled(abort_func))).unwrap()
  File "C:\Users\mozesa\PycharmProjects\asm-v316-web\.venv\lib\site-packages\outcome\_sync.py", line 111, in unwrap
    raise captured_error
  File "C:\Users\mozesa\PycharmProjects\asm-v316-web\.venv\lib\site-packages\trio\_core\_run.py", line 1167, in raise_cancel
    raise Cancelled._create()
trio.Cancelled: Cancelled

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mozesa\PycharmProjects\asm-v316-web\.venv\lib\site-packages\trio\_core\_run.py", line 2181, in unrolled_run
    runner.task_exited(task, final_outcome)
  File "C:\Users\mozesa\PycharmProjects\asm-v316-web\.venv\lib\site-packages\trio\_core\_run.py", line 1506, in task_exited
    outcome.unwrap()
  File "C:\Users\mozesa\PycharmProjects\asm-v316-web\.venv\lib\site-packages\outcome\_sync.py", line 111, in unwrap
    raise captured_error
  File "C:\Users\mozesa\PycharmProjects\asm-v316-web\.venv\lib\site-packages\trio\_core\_run.py", line 1599, in init
    run_sync_soon_nursery.cancel_scope.cancel()
  File "C:\Users\mozesa\PycharmProjects\asm-v316-web\.venv\lib\site-packages\trio\_core\_run.py", line 815, in __aexit__
    raise combined_error_from_nursery
  File "C:\Users\mozesa\PycharmProjects\asm-v316-web\.venv\lib\site-packages\trio\_core\_entry_queue.py", line 57, in kill_everything
    raise exc
  File "C:\Users\mozesa\PycharmProjects\asm-v316-web\.venv\lib\site-packages\trio\_core\_entry_queue.py", line 53, in run_cb
    sync_fn(*args)
  File "C:\Users\mozesa\PycharmProjects\asm-v316-web\.venv\lib\site-packages\trio\_threads.py", line 282, in callback
    trio.lowlevel.spawn_system_task(await_in_trio_thread_task, name=afn)
  File "C:\Users\mozesa\PycharmProjects\asm-v316-web\.venv\lib\site-packages\trio\_core\_generated_run.py", line 146, in spawn_system_task
    return GLOBAL_RUN_CONTEXT.runner.spawn_system_task(async_fn, *args, name=name)
  File "C:\Users\mozesa\PycharmProjects\asm-v316-web\.venv\lib\site-packages\trio\_core\_run.py", line 1564, in spawn_system_task
    return self.spawn_impl(
  File "C:\Users\mozesa\PycharmProjects\asm-v316-web\.venv\lib\site-packages\trio\_core\_run.py", line 1424, in spawn_impl
    raise RuntimeError("Nursery is closed to new arrivals")
RuntimeError: Nursery is closed to new arrivals

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:/Users/mozesa/PycharmProjects/asm-v316-web/asm_v316_web/__init__.py", line 30, in <module>
    trio.run(main)
  File "C:\Users\mozesa\PycharmProjects\asm-v316-web\.venv\lib\site-packages\trio\_core\_run.py", line 1919, in run
    timeout = gen.send(next_send)
  File "C:\Users\mozesa\PycharmProjects\asm-v316-web\.venv\lib\site-packages\trio\_core\_run.py", line 2226, in unrolled_run
    raise TrioInternalError("internal error in Trio - please file a bug!") from exc
trio.TrioInternalError: internal error in Trio - please file a bug!

Process finished with exit code 1
```

**Comment by RazerM** [comment]
I can confirm this happens on trio 0.17 but not 0.16.
